### ISSUE TITLE
Update the points command to not have a number rank on an appended caller

### ISSUE THREAD

**Issue by waream2** [coding-buddies-discord/cb-bots#71]
If a caller is not in the top 8 but appended to the report, let's strip out their number. They arent actually 9th

**Comment by Claudi0-V** [comment]
if the person is the caller, they may want to know what position in the table they'll be, but right now it shows the person as the #9, even if they were the 100. 

To solve this will require to change how the call for mongo works, and maybe refactoring all calls to also improve speed and reduce db calls, and since I was already going to make this, I have no issue taking
